dist: xenial

language: go

go:
  - 1.13.x
  - 1.12.x

env:
  - GO111MODULE=on

install: true

script:
  - go test -bench=. -benchmem ./...

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
